#' Resources and citation UI for fisheriesXplorer
#'
#' This module UI builds the "Resources" section of the \code{fisheriesXplorer}
#' app. It provides tabs for contact and feedback, data sources and FAIR
#' information, data disclaimer and policy, and application citation details.
#' The UI includes embedded external forms, links to ICES data services, and
#' preformatted citation text (including BibTeX and CSL-JSON).
#'
#' @param id A character string used as the module namespace. Passed to
#'   \code{shiny::NS()} and used to namespace all UI and server elements
#'   within the module.
#'
#' @details
#' The module is organised into multiple \code{bslib::nav_panel()} views:
#' \itemize{
#'   \item \emph{Contact & Feedback}: email link and embedded Microsoft Forms
#'     feedback form.
#'   \item \emph{Data Sources}: a grid of resource cards describing ICES data
#'     services, application source code, and connected tools, with links to
#'     landing pages, metadata and APIs.
#'   \item \emph{Data disclaimer & policy}: a disclaimer block created by
#'     \code{make_disclaimer_block()}.
#'   \item \emph{Citation}: human- and machine-readable citation information
#'     generated by \code{build_app_citation()}, including JSON-LD markup.
#' }
#'
#' Helper functions such as \code{build_app_citation()}, \code{resource_card()},
#' and \code{make_disclaimer_block()} are expected to be defined elsewhere in
#' the package.
#'
#' @return A \code{bslib::navset_tab()} UI object representing the resources
#'   and citation section of the application.
#'
#' @importFrom shiny NS tagList tags icon a div h3 h4 p
#' @importFrom bslib navset_tab nav_panel
#'
#' @export
mod_resources_ui <- function(id) {
  ns <- NS(id)
  repo_url <- "https://github.com/ices-tools-prod/fisheriesXplorer"
  # Build the citation strings for display
  app_cite <- build_app_citation()

  bslib::navset_tab(
    id = ns("resources_nav"),

    # --- Contact & Feedback
    # --- Contact & Feedback
bslib::nav_panel(
  tagList(icon("envelope"), "Contact & Feedback"),
  div(
    class = "resources-page",
    h3(HTML("<b>Contact & Feedback</b>")),
    p("We’d love to hear from you. For questions, bug reports, or suggestions:"),
    tags$ul(
      tags$li(HTML("Email: <a href='mailto:luca.lamoni@ices.dk'>luca.lamoni@ices.dk</a>"))
    ),
    p("Or fill out the form below:"),
    div(
      class = "msform-embed",
      tags$iframe(
        src = "https://forms.office.com/e/vF0shUzLRk?embed=true",
        width = "640px", height = "480px", frameborder = "0",
        marginwidth = "0", marginheight = "0",
        style = "border: none; max-width:100%; max-height:100vh",
        loading = "lazy", allowfullscreen = NA, webkitallowfullscreen = NA,
        mozallowfullscreen = NA, msallowfullscreen = NA
      )
    ),
    p(
      em("Having trouble submitting inside the app? "),
      a(
        "Open the form in a new tab.",
        href = "https://forms.office.com/e/vF0shUzLRk",
        target = "_blank", rel = "noopener"
      )
    )
  )
),


    bslib::nav_panel(
      tagList(icon("database"), "Data Sources"),
      div(
        class = "resources-page",

        # Intro
        div(
          class = "intro-card",
          h3(HTML("<b>About these data</b>")),
          p(
            "fisheriesXplorer displays (and cites) data from ICES services.",
            " Each source below lists what is used, where it comes from, how to access it, and how to cite/reuse it."
          )
        ),

        # Grid of standardized cards
        div(
          class = "resources-grid",

          # 1) ICES Spatial Facility
          resource_card(
            title = "ICES Spatial Facility (maps)",
            description = "Ecoregion layers and spatial context used across the app.",
            dataset_url = "https://gis.ices.dk/sf/index.html",
            metadata_url = "https://gis.ices.dk/geonetwork/srv/api/records/4745e824-a612-4a1f-bc56-b540772166eb?language=all",
            services = list("Ecoregions shapefiles (zip)" = "https://gis.ices.dk/shapefiles/ICES_ecoregions.zip"),
            notes = "See dataset page for data access and conditions."
          ),

          # 2) Stock Information Database (SID)
          resource_card(
            title = "Stock Information Database (SID)",
            description = "Used to resolve stock metadata and keys used across the app.",
            dataset_url = "http://sid.ices.dk",
            metadata_url = "https://gis.ices.dk/geonetwork/srv/api/records/ec374765-55e8-401a-b219-e011b231ae1b?language=all",
            services = list("APIs" = "http://sid.ices.dk/services/"),
            notes = "See dataset page for data access and conditions."
          ),

          # 3) Stock Assessment Graphs (SAG)
          resource_card(
            title = "Stock Assessment Graphs (SAG)",
            description = "Assessment outputs and status indicators (e.g., F/FMSY, SSB/MSY Btrigger) shown in status and trends views.",
            dataset_url = "https://www.ices.dk/data/assessment-tools/Pages/stock-assessment-graphs.aspx",
            metadata_url = "https://gis.ices.dk/geonetwork/srv/api/records/f5992b7d-b9da-40d4-81b9-d6db9e87e759?language=all",
            services = list("APIs" = "https://sag.ices.dk/sag_api/docs/swagger/index.html"),
            notes = "See dataset page for data access and conditions."
          ),

          # 4) Landings / Catch series
          resource_card(
            title = "Historical and Nominal catches",
            description = "Compiled landings (and related series) used in the Landings results.",
            dataset_url = "https://www.ices.dk/data/dataset-collections/Pages/Fish-catch-and-stock-assessment.aspx",
            metadata_url = "https://gis.ices.dk/geonetwork/srv/api/records/7d242743-1069-417b-81e3-57f25c791a26",
            notes = "See dataset page for data access and conditions."
          ),

          # 5) VMS Data
          resource_card(
            title = "VMS and Logbook dataset",
            description = "Aggregated VMS-based effort and physical disturbance data used in the VMS results.",
            dataset_url = "https://data.ices.dk/vms",
            metadata_url = "https://gis.ices.dk/geonetwork/srv/api/records/60d06467-7545-4a06-86ab-2a2ababd3e0a?language=all",
            services = list(APIs = "https://data.ices.dk/vms/webservices"),
            notes = "See dataset page for data access and conditions."
          ),

          # 6) Bycatch Data
          resource_card(
            title = "Bycatch dataset",
            description = "Results from ICES advice on bycatch of protected, endangered and threatened species.",
            dataset_url = "https://www.ices.dk/data/data-portals/Pages/Bycatch.aspx",
            metadata_url = "https://gis.ices.dk/geonetwork/srv/api/records/f11f65af-904f-49d7-90c4-8ce8156b375b?language=all",
            services = list(APIs = "https://bycatch.ices.dk/BycatchAdvice"),
            notes = "See dataset page for data access and conditions."
          ),

          # 7) Application source code (not a dataset, but important for reuse)
          resource_card(
            title = "Application source code",
            description = "Code for this application (versioning, issues, reproducibility).",
            services = list("GitHub" = "https://github.com/ices-tools-dev/fisheriesXplorer"),
            notes = "This application is open source under the MIT license. See the repository for code, issues, and contribution guidelines."
          ),
          # 8) Connected applications (e.g., adviceXplorer)
          resource_card(
            title = "Connected applications",
            description = "This app integrates with other ICES tools for data or embedded components.",
            services = list("adviceXplorer" = "https://ices-taf.shinyapps.io/advicexplorer/"),
            notes = "See the relevant application metadata record for details on data sources and terms."
          )
        ),

        # FAIR checklist
        div(
          class = "fair-card",
          h4("FAIR at a glance"),
          tags$ul(
            tags$li(HTML("<b>Findable</b>: clear titles, landing pages, and a metadata record.")),
            tags$li(HTML("<b>Accessible</b>: direct links to landing pages and services.")),
            tags$li(HTML("<b>Interoperable</b>: machine-readable formats (CSV/JSON) and documented schemas.")),
            tags$li(HTML("<b>Reusable</b>: citation text, version/build info, and licensing notes."))
          )
        )
      ),

      # Optional JSON-LD (kept from your version)
      tags$script(
        type = "application/ld+json",
        HTML(jsonlite::toJSON(
          list(
            "@context" = "https://schema.org", "@type" = "Dataset",
            "name" = "ICES Fish catch and stock assessment dataset",
            "url" = "https://www.ices.dk/data/dataset-collections/Pages/Fish-catch-and-stock-assessment.aspx",
            "identifier" = "https://gis.ices.dk/geonetwork/srv/api/records/7d242743-1069-417b-81e3-57f25c791a26",
            "publisher" = list("@type" = "Organization", "name" = "ICES"),
            "license" = "See dataset page",
            "isAccessibleForFree" = TRUE
          ),
          auto_unbox = TRUE, pretty = TRUE
        ))
      )
    ),
    bslib::nav_panel(
      tagList(icon("exclamation-triangle"), "Data disclaimer & policy"),
      make_disclaimer_block()
    ),
    bslib::nav_panel(
      tagList(icon("quote-right"), "Citation"),
      div(class = "cite-card",
        div(class = "cite-title", h3(HTML("<b>How to cite this application</b>"))),
        p("Please cite the application to support reproducibility:"),
        div(class = "codeblock", app_cite$text),

        tags$details(
          tags$summary("BibTeX"),
          div(class = "codeblock", app_cite$bibtex)
        ),
        tags$details(
          tags$summary("CSL-JSON"),
          div(class = "codeblock", jsonlite::toJSON(app_cite$csl, auto_unbox = TRUE, pretty = TRUE))
        ),

        div(class = "cite-actions",
          downloadButton(ns("dl_citations_txt"), "Download TXT"),
          downloadButton(ns("dl_citations_bib"), "Download BibTeX"),
          downloadButton(ns("dl_citations_csl"), "Download CSL-JSON")
        ),

        # Optional: machine-readable JSON-LD for the app
        tags$script(
          type = "application/ld+json",
          HTML(jsonlite::toJSON(
            list(
              "@context"="https://schema.org",
              "@type"="SoftwareApplication",
              "name"="fisheriesXplorer",
              "applicationCategory"="DataVisualization",
              "url"="https://ices-tools-dev.shinyapps.io/fisheriesXplorer/",
              "publisher"=list("@type"="Organization","name"="ICES"),
              "license"="https://creativecommons.org/licenses/by/4.0/"
            ), auto_unbox = TRUE, pretty = TRUE))
        )
      )
    )
  )
}


#' Server logic for the resources and citation module
#'
#' This module server wires up bookmarking behaviour for the overview tabs
#' and provides download handlers for the application citation in multiple
#' formats (plain text, BibTeX, CSL-JSON).
#'
#' @param id Module id, passed from \code{mod_resources_ui()}.
#' @param bookmark_qs A reactive returning a list of query-string bookmark
#'   parameters (typically including \code{subtab}), or \code{NULL}. Used to
#'   restore the selected overview tab on load.
#' @param set_subtab A callback function that accepts a single argument,
#'   the current subtab id. Used to report overview tab changes back to the
#'   parent app for bookmarking or other side effects.
#'
#' @details
#' On initial load, the module:
#' \itemize{
#'   \item Reads the desired subtab from \code{bookmark_qs()} (field
#'   \code{subtab}) and, if valid, updates \code{tabs_overview} after the
#'   first \code{session$onFlushed()}.
#'   \item Calls \code{set_subtab()} once to synchronise the restored state
#'   with the parent.
#' }
#'
#' During the session, changes to \code{input$tabs_overview} are observed and
#' reported via \code{set_subtab()} (ignoring the initial default selection).
#'
#' The module also builds the application citation via
#' \code{build_app_citation()} and exposes three download handlers:
#' \code{dl_citations_txt}, \code{dl_citations_bib}, and
#' \code{dl_citations_csl}.
#'
#' @return No direct return value; called for its side effects of registering
#'   observers and download handlers within a Shiny server context.
#'
#' @importFrom shiny moduleServer observeEvent updateTabsetPanel downloadHandler
#'
#' @export
mod_resources_server <- function(
  id,
  bookmark_qs = reactive(NULL),
  set_subtab = function(...) {}) {
  moduleServer(id, function(input, output, session) {

    ################################## bookmarking #########################################
    # This module participates in the global bookmarking via two hooks:
    # - `bookmark_qs`: a reactive list provided by the main server with the
    #   parsed query-string (including $subtab).
    # - `set_subtab()`: a callback into the main server to report *user-driven*
    #   changes of the internal tab state.
    #
    # Restore path:
    # - On first non-null bookmark_qs(), we read the desired subtab.
    # - If it is valid for this module, we wait for the UI to flush, then
    #   select the corresponding tabsetPanel value.
    # - We also call set_subtab() once so the main server can see that the
    #   module has accepted the requested subtab.
    #
    # Report path:
    # - Any later changes to input$tabs_overview (ignoring the initial) are
    #   forwarded upstream via set_subtab(), so the main server can update
    #   the URL hash / desired() state.
    observeEvent(bookmark_qs(), once = TRUE, ignoreInit = TRUE, {
      qs <- bookmark_qs()
      wanted <- qs$subtab
      valid <- c("exec_summary", "introduction", "who_is_fishing")
      if (!is.null(wanted) && nzchar(wanted) && wanted %in% valid) {
        session$onFlushed(function() {
          updateTabsetPanel(session, "tabs_overview", selected = wanted)
          isolate(set_subtab(wanted)) # one-arg setter
        }, once = TRUE)
      }
    })
    
    # REPORT on user changes, skip initial default
    observeEvent(input$tabs_overview,
      {
        set_subtab(input$tabs_overview) # one arg only
      },
      ignoreInit = TRUE
    )

    app_cite <- build_app_citation()

    output$dl_citations_txt <- downloadHandler(
      filename = function() sprintf("fisheriesXplorer_citation_%s.txt", Sys.Date()),
      content  = function(file) writeLines(app_cite$text, file)
    )

    output$dl_citations_bib <- downloadHandler(
      filename = function() sprintf("fisheriesXplorer_citation_%s.bib", Sys.Date()),
      content  = function(file) writeLines(app_cite$bibtex, file)
    )

    output$dl_citations_csl <- downloadHandler(
      filename = function() sprintf("fisheriesXplorer_citation_%s.json", Sys.Date()),
      content  = function(file) writeLines(jsonlite::toJSON(app_cite$csl, auto_unbox = TRUE, pretty = TRUE), file)
    )
  })
}
#-- end of mod_resources.R --#